# pnpm-workspace.yaml
packages:
    - 'packages/*'
    - '!**/test/**'

catalog:
    'viem': '^2.43.3'
    'chalk': '4.1.2'
    'dotenv': '^17.2.3'
    'node-cache': '5.1.2'
    'node-fetch': '^3.3.2'
    'ws': '^8.18.0'
    '@types/ws': '^8.5.14'
    'axios': '^1.7.9'
    'date-fns': '^4.1.0'
    'date-fns-tz': '^3.2.0'
